- hosts:  all
  become: yes

  vars:
    node_ver: '6'

  tasks:

    - name: add gradle ppa
      apt_repository: 
        repo: 'ppa:cwchien/gradle'
        update_cache: yes
      tags:
        - gradle
        - minimal
        - latest
        - full

    - name: install gradle
      package: 
        name: gradle 
        state: present
      tags:
        - gradle
        - minimal
        - latest
        - full

    - name: install node repo
      shell: curl -sL https://deb.nodesource.com/setup_{{ node_ver }}.x | sudo -E bash -
      tags: 
        - node
        - minimal
        - latest
        - full
   
    - name: install nodejs
      package: 
        name: nodejs 
        state: present
      tags: 
        - node
        - minimal
        - latest
        - full

    - name: Install node.js packages globally
      npm:
        name: "{{ item }}"
        global: yes
      tags:
        - node
        - minimal
        - latest
        - full
      with_items:
        - node-gyp
        - webdriver-manager
        - gulp
        - rollup
        - bower
        - node-sass
        - karma
       
    - name: install glue-sprite
      package: 
        name: glue-sprite 
        state: present
      tags:
        - glue
        - minimal
        - latest
        - full

    - name: install packages for glue-sprite
      package: 
        name: "{{ item }}"
        state: present
      tags:
        - glue
        - minimal
        - latest
        - full
      with_items:
        - python-dev
        - python-setuptools
        - python-pip
        - python3-dev
        - python3-setuptools
        - python3-pip

    - name: install pip packages for glue-sprite
      shell: pip install --upgrade pip; pip install glue; pip3 install --upgrade pip; pip3 install glue
      tags:
        - glue
        - minimal
        - latest
        - full

    - name: add docker apt key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
      tags:
        - docker
        - minimal
        - latest
        - full

    - name: add docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: 'docker-stable'
        update_cache: yes
      tags:
        - docker
        - minimal
        - latest
        - full

    - name: install docker
      package:
        name: docker-ce
        state: present
      tags:
        - docker
        - minimal
        - latest
        - full

    - name: install python packages for docker
      package: 
        name: "{{ item }}"
        state: installed
      tags:
        - docker
        - minimal
        - latest
        - full
      with_items:
        - python-requests
        - python-requestsexceptions
        - python-docker

    - name: install conversion libs
      package: 
        name: "{{ item }}"
      tags:
        - libs
        - full
      with_items:
        - libreoffice
        - libtiff-tools
        - ghostscript

    - name: install various packages
      package: 
        name: "{{ item }}"
      tags:
        - packages
        - minimal
        - latest
        - full
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - s3cmd
        - ngrok-client
        - zsh
        - nano
        - wget
        - ant

    - name: install postgresql packages
      package:
        name: "{{ item }}"
      tags:
        - postgres
        - db
        - full
      with_items:
        - postgresql
        - postgresql-client

    - name: install mysql packages
      package:
        name: "{{ item }}"
      tags:
        - mysql
        - db
        - full
      with_items:
        - mysql-server
        - python-mysqldb
        - mysql-client

    - name: install pt command line
      shell: pip install git+https://github.com/egis/papertrail-python-cli.git
      tags:
        - pt
        - minimal
        - latest
        - full

    - name: install pt command line for python 2.7
      shell: pip2.7 install git+https://github.com/egis/papertrail-python-cli.git
      tags:
        - pt
        - minimal
        - latest
        - full
