- hosts:  all
  become: yes

  vars:
    node_ver: '18'

  tasks:

    - name: install system packages
      package:
        name: "{{ item }}"
      with_items:
        - ca-certificates
        - ghostscript
        - locales
        - openssh-client
        - tar
        - gzip
        - parallel
        - net-tools
        - netcat
        - unzip
        - zip
        - bzip2
        - postgresql-client
      tags:
        - system-packages


    - name: add ppa's
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - ppa:cwchien/gradle
      tags:
        - system-packages

    - name: add docker apt key
      apt_key:
        url: "{{ item }}"
        state: present
      with_items:
        - https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        - https://download.docker.com/linux/ubuntu/gpg
      tags:
        - system-packages


    - name: add docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: 'docker-stable'
      tags:
        - system-packages


    - name: add nodejs repository
      shell: "curl -sL https://deb.nodesource.com/setup_{{node_ver}}.x | sudo -E bash -"
      tags:
        - system-packages


    - name: install build packages
      package:
        name: "{{ item }}"
        update_cache: true
      with_items:
        - nodejs
        - gradle
        - ant
        - s3cmd
        - ngrok-client
        - zsh
        - ant
        - python-requests
        - python-requestsexceptions
        - python-docker


    - name: Install node.js packages globally
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - node-gyp
        - webdriver-manager
        - gulp
        - rollup
        - bower
        - node-sass
        - karma


    - name: Install pip packages
      pip:
        name: "{{ item }}"
        with_items:
          - papertrail-cli
          - httpie
          - jq

    - name: download codacy coverage reporter
      get_url:
        url: https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.0/codacy-coverage-reporter-2.0.0-assembly.jar
        dest: /opt/codacy
        force_basic_auth: yes
      tags:
        - codacy
